encoding: UTF-8
lang: vi
timezone: Asia/Ho_Chi_Minh
title: NetTV
email: tri.vh15@gmail.com
description: NetTV Blog
author: Lạc Trần
baseurl: ''
url: n-tv.github.io
twitter_username: null
github_username: n-tv
facebook_username: null
instagram_username: null
linkedin_username: null
google_analytics: UA-XXXXXXXXX-X
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
compress_html:
  comments:
    - <!--
    - '-->'
  blanklines: true
sass:
  sass_dir: _sass
  style: ':compressed'
permalink: '/:categories/:title'
