title:              NetTV
email:              your-email@example.com
description:        Home
author:             Start Bootstrap
baseurl:            "/n-tv"
url:                "https://n-tv.github.io"

# Social Profiles
twitter_username:   Bootstrap
github_username:    n-tv
facebook_username:  n-tv
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
