timezone: Asia/Ho_Chi_Minh
title:              NetTV
email:              tri.vh15@gmail.com
description:        NetTV Blog
author:             Lạc Trần
baseurl:            ""
url:                "https://n-tv.github.io"
# Hồ sơ xã hội
twitter_username:   
github_username:    n-tv
facebook_username:  
instagram_username:  
linkedin_username:
# Thêm ID google-analytics của bạn tại đây để kích hoạt google analytics
google_analytics:   UA-XXXXXXXXX-X # ra mã google-analytics của bạn
# Xây dựng cài đặt
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Bỏ ghi chú dòng này để âm thầm tạo một sơ đồ trang web tuân thủ sitemaps.org cho trang web Jekyll của bạn
sass:
    sass_dir: _sass
    style: compressed
# html minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
